linters:
  enable:
    - gofmt
    - revive    # pengganti golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign

run:
  deadline: 5m

issues:
  exclude-use-default: false
